export const countries = [
  {
    name: 'Afghanistan',
    code: 'AFG',
    alpha2Code: 'AF',
    numericCode: 4,
    region: 'Asia',
    subregion: 'Southern Asia',
  },
  {
    name: 'Åland Islands',
    code: 'ALA',
    alpha2Code: 'AX',
    numericCode: 248,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Albania',
    code: 'ALB',
    alpha2Code: 'AL',
    numericCode: 8,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Algeria',
    code: 'DZA',
    alpha2Code: 'DZ',
    numericCode: 12,
    region: 'Africa',
    subregion: 'Northern Africa',
  },
  {
    name: 'American Samoa',
    code: 'ASM',
    alpha2Code: 'AS',
    numericCode: 16,
    region: 'Oceania',
    subregion: 'Polynesia',
  },
  {
    name: 'Andorra',
    code: 'AND',
    alpha2Code: 'AD',
    numericCode: 20,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Angola',
    code: 'AGO',
    alpha2Code: 'AO',
    numericCode: 24,
    region: 'Africa',
    subregion: 'Sub-Saharan Africa',
  },
  {
    name: 'Anguilla',
    code: 'AIA',
    alpha2Code: 'AI',
    numericCode: 660,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Antarctica',
    code: 'ATA',
    alpha2Code: 'AQ',
    numericCode: 10,
    region: 'Polar',
    subregion: '',
  },
  {
    name: 'Antigua and Barbuda',
    code: 'ATG',
    alpha2Code: 'AG',
    numericCode: 28,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Argentina',
    code: 'ARG',
    alpha2Code: 'AR',
    numericCode: 32,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'Armenia',
    code: 'ARM',
    alpha2Code: 'AM',
    numericCode: 51,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Aruba',
    code: 'ABW',
    alpha2Code: 'AW',
    numericCode: 533,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Australia',
    code: 'AUS',
    alpha2Code: 'AU',
    numericCode: 36,
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
  },
  {
    name: 'Austria',
    code: 'AUT',
    alpha2Code: 'AT',
    numericCode: 40,
    region: 'Europe',
    subregion: 'Western Europe',
  },
  {
    name: 'Azerbaijan',
    code: 'AZE',
    alpha2Code: 'AZ',
    numericCode: 31,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Bahamas',
    code: 'BHS',
    alpha2Code: 'BS',
    numericCode: 44,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Bahrain',
    code: 'BHR',
    alpha2Code: 'BH',
    numericCode: 48,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Bangladesh',
    code: 'BGD',
    alpha2Code: 'BD',
    numericCode: 50,
    region: 'Asia',
    subregion: 'Southern Asia',
  },
  {
    name: 'Barbados',
    code: 'BRB',
    alpha2Code: 'BB',
    numericCode: 52,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Belarus',
    code: 'BLR',
    alpha2Code: 'BY',
    numericCode: 112,
    region: 'Europe',
    subregion: 'Eastern Europe',
  },
  {
    name: 'Belgium',
    code: 'BEL',
    alpha2Code: 'BE',
    numericCode: 56,
    region: 'Europe',
    subregion: 'Western Europe',
  },
  {
    name: 'Belize',
    code: 'BLZ',
    alpha2Code: 'BZ',
    numericCode: 84,
    region: 'Americas',
    subregion: 'Central America',
  },
  {
    name: 'Benin',
    code: 'BEN',
    alpha2Code: 'BJ',
    numericCode: 204,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Bermuda',
    code: 'BMU',
    alpha2Code: 'BM',
    numericCode: 60,
    region: 'Americas',
    subregion: 'Northern America',
  },
  {
    name: 'Bhutan',
    code: 'BTN',
    alpha2Code: 'BT',
    numericCode: 64,
    region: 'Asia',
    subregion: 'Southern Asia',
  },
  {
    name: 'Bolivia',
    code: 'BOL',
    alpha2Code: 'BO',
    numericCode: 68,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    code: 'BES',
    alpha2Code: 'BQ',
    numericCode: 535,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BIH',
    alpha2Code: 'BA',
    numericCode: 70,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Botswana',
    code: 'BWA',
    alpha2Code: 'BW',
    numericCode: 72,
    region: 'Africa',
    subregion: 'Southern Africa',
  },
  {
    name: 'Bouvet Island',
    code: 'BVT',
    alpha2Code: 'BV',
    numericCode: 74,
    region: 'Antarctica',
    subregion: '',
  },
  {
    name: 'Brazil',
    code: 'BRA',
    alpha2Code: 'BR',
    numericCode: 76,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'British Indian Ocean Territory',
    code: 'IOT',
    alpha2Code: 'IO',
    numericCode: 86,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Brunei Darussalam',
    code: 'BRN',
    alpha2Code: 'BN',
    numericCode: 96,
    region: 'Asia',
    subregion: 'South-Eastern Asia',
  },
  {
    name: 'Bulgaria',
    code: 'BGR',
    alpha2Code: 'BG',
    numericCode: 100,
    region: 'Europe',
    subregion: 'Eastern Europe',
  },
  {
    name: 'Burkina Faso',
    code: 'BFA',
    alpha2Code: 'BF',
    numericCode: 854,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Burundi',
    code: 'BDI',
    alpha2Code: 'BI',
    numericCode: 108,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Cabo Verde',
    code: 'CPV',
    alpha2Code: 'CV',
    numericCode: 132,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Cambodia',
    code: 'KHM',
    alpha2Code: 'KH',
    numericCode: 116,
    region: 'Asia',
    subregion: 'South-Eastern Asia',
  },
  {
    name: 'Cameroon',
    code: 'CMR',
    alpha2Code: 'CM',
    numericCode: 120,
    region: 'Africa',
    subregion: 'Middle Africa',
  },
  {
    name: 'Canada',
    code: 'CAN',
    alpha2Code: 'CA',
    numericCode: 124,
    region: 'Americas',
    subregion: 'Northern America',
  },
  {
    name: 'Cayman Islands',
    code: 'CYM',
    alpha2Code: 'KY',
    numericCode: 136,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Central African Republic',
    code: 'CAF',
    alpha2Code: 'CF',
    numericCode: 140,
    region: 'Africa',
    subregion: 'Middle Africa',
  },
  {
    name: 'Chad',
    code: 'TCD',
    alpha2Code: 'TD',
    numericCode: 148,
    region: 'Africa',
    subregion: 'Middle Africa',
  },
  {
    name: 'Chile',
    code: 'CHL',
    alpha2Code: 'CL',
    numericCode: 152,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'China',
    code: 'CHN',
    alpha2Code: 'CN',
    numericCode: 156,
    region: 'Asia',
    subregion: 'Eastern Asia',
  },
  {
    name: 'Christmas Island',
    code: 'CXR',
    alpha2Code: 'CX',
    numericCode: 162,
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
  },
  {
    name: 'Cocos (Keeling) Islands',
    code: 'CCK',
    alpha2Code: 'CC',
    numericCode: 166,
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
  },
  {
    name: 'Colombia',
    code: 'COL',
    alpha2Code: 'CO',
    numericCode: 170,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'Comoros',
    code: 'COM',
    alpha2Code: 'KM',
    numericCode: 174,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Congo',
    code: 'COG',
    alpha2Code: 'CG',
    numericCode: 178,
    region: 'Africa',
    subregion: 'Middle Africa',
  },
  {
    name: 'Congo (Democratic Republic of the)',
    code: 'COD',
    alpha2Code: 'CD',
    numericCode: 180,
    region: 'Africa',
    subregion: 'Middle Africa',
  },
  {
    name: 'Cook Islands',
    code: 'COK',
    alpha2Code: 'CK',
    numericCode: 184,
    region: 'Oceania',
    subregion: 'Polynesia',
  },
  {
    name: 'Costa Rica',
    code: 'CRI',
    alpha2Code: 'CR',
    numericCode: 188,
    region: 'Americas',
    subregion: 'Central America',
  },
  {
    name: 'Croatia',
    code: 'HRV',
    alpha2Code: 'HR',
    numericCode: 191,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Cuba',
    code: 'CUB',
    alpha2Code: 'CU',
    numericCode: 192,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Curaçao',
    code: 'CUW',
    alpha2Code: 'CW',
    numericCode: 531,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Cyprus',
    code: 'CYP',
    alpha2Code: 'CY',
    numericCode: 196,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Czech Republic',
    code: 'CZE',
    alpha2Code: 'CZ',
    numericCode: 203,
    region: 'Europe',
    subregion: 'Eastern Europe',
  },
  {
    name: 'Denmark',
    code: 'DNK',
    alpha2Code: 'DK',
    numericCode: 208,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Djibouti',
    code: 'DJI',
    alpha2Code: 'DJ',
    numericCode: 262,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Dominica',
    code: 'DMA',
    alpha2Code: 'DM',
    numericCode: 212,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Dominican Republic',
    code: 'DOM',
    alpha2Code: 'DO',
    numericCode: 214,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Ecuador',
    code: 'ECU',
    alpha2Code: 'EC',
    numericCode: 218,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'Egypt',
    code: 'EGY',
    alpha2Code: 'EG',
    numericCode: 818,
    region: 'Africa',
    subregion: 'Northern Africa',
  },
  {
    name: 'El Salvador',
    code: 'SLV',
    alpha2Code: 'SV',
    numericCode: 222,
    region: 'Americas',
    subregion: 'Central America',
  },
  {
    name: 'Equatorial Guinea',
    code: 'GNQ',
    alpha2Code: 'GQ',
    numericCode: 226,
    region: 'Africa',
    subregion: 'Middle Africa',
  },
  {
    name: 'Eritrea',
    code: 'ERI',
    alpha2Code: 'ER',
    numericCode: 232,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Estonia',
    code: 'EST',
    alpha2Code: 'EE',
    numericCode: 233,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Ethiopia',
    code: 'ETH',
    alpha2Code: 'ET',
    numericCode: 231,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    code: 'FLK',
    alpha2Code: 'FK',
    numericCode: 238,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'Faroe Islands',
    code: 'FRO',
    alpha2Code: 'FO',
    numericCode: 234,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Fiji',
    code: 'FJI',
    alpha2Code: 'FJ',
    numericCode: 242,
    region: 'Oceania',
    subregion: 'Melanesia',
  },
  {
    name: 'Finland',
    code: 'FIN',
    alpha2Code: 'FI',
    numericCode: 246,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'France',
    code: 'FRA',
    alpha2Code: 'FR',
    numericCode: 250,
    region: 'Europe',
    subregion: 'Western Europe',
  },
  {
    name: 'French Guiana',
    code: 'GUF',
    alpha2Code: 'GF',
    numericCode: 254,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'French Polynesia',
    code: 'PYF',
    alpha2Code: 'PF',
    numericCode: 258,
    region: 'Oceania',
    subregion: 'Polynesia',
  },
  {
    name: 'French Southern Territories',
    code: 'ATF',
    alpha2Code: 'TF',
    numericCode: 260,
    region: 'Africa',
    subregion: 'Southern Africa',
  },
  {
    name: 'Gabon',
    code: 'GAB',
    alpha2Code: 'GA',
    numericCode: 266,
    region: 'Africa',
    subregion: 'Middle Africa',
  },
  {
    name: 'Gambia',
    code: 'GMB',
    alpha2Code: 'GM',
    numericCode: 270,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Georgia',
    code: 'GEO',
    alpha2Code: 'GE',
    numericCode: 268,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Germany',
    code: 'DEU',
    alpha2Code: 'DE',
    numericCode: 276,
    region: 'Europe',
    subregion: 'Western Europe',
  },
  {
    name: 'Ghana',
    code: 'GHA',
    alpha2Code: 'GH',
    numericCode: 288,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Gibraltar',
    code: 'GIB',
    alpha2Code: 'GI',
    numericCode: 292,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Greece',
    code: 'GRC',
    alpha2Code: 'GR',
    numericCode: 300,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Greenland',
    code: 'GRL',
    alpha2Code: 'GL',
    numericCode: 304,
    region: 'Americas',
    subregion: 'Northern America',
  },
  {
    name: 'Grenada',
    code: 'GRD',
    alpha2Code: 'GD',
    numericCode: 308,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Guadeloupe',
    code: 'GLP',
    alpha2Code: 'GP',
    numericCode: 312,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Guam',
    code: 'GUM',
    alpha2Code: 'GU',
    numericCode: 316,
    region: 'Oceania',
    subregion: 'Micronesia',
  },
  {
    name: 'Guatemala',
    code: 'GTM',
    alpha2Code: 'GT',
    numericCode: 320,
    region: 'Americas',
    subregion: 'Central America',
  },
  {
    name: 'Guernsey',
    code: 'GGY',
    alpha2Code: 'GG',
    numericCode: 831,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Guinea',
    code: 'GIN',
    alpha2Code: 'GN',
    numericCode: 324,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Guinea-Bissau',
    code: 'GNB',
    alpha2Code: 'GW',
    numericCode: 624,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Guyana',
    code: 'GUY',
    alpha2Code: 'GY',
    numericCode: 328,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'Haiti',
    code: 'HTI',
    alpha2Code: 'HT',
    numericCode: 332,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Heard Island and McDonald Islands',
    code: 'HMD',
    alpha2Code: 'HM',
    numericCode: 334,
    region: 'Antarctica',
    subregion: '',
  },
  {
    name: 'Holy See',
    code: 'VAT',
    alpha2Code: 'VA',
    numericCode: 336,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Honduras',
    code: 'HND',
    alpha2Code: 'HN',
    numericCode: 340,
    region: 'Americas',
    subregion: 'Central America',
  },
  {
    name: 'Hong Kong',
    code: 'HKG',
    alpha2Code: 'HK',
    numericCode: 344,
    region: 'Asia',
    subregion: 'Eastern Asia',
  },
  {
    name: 'Hungary',
    code: 'HUN',
    alpha2Code: 'HU',
    numericCode: 348,
    region: 'Europe',
    subregion: 'Eastern Europe',
  },
  {
    name: 'Iceland',
    code: 'ISL',
    alpha2Code: 'IS',
    numericCode: 352,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'India',
    code: 'IND',
    alpha2Code: 'IN',
    numericCode: 356,
    region: 'Asia',
    subregion: 'Southern Asia',
  },
  {
    name: 'Indonesia',
    code: 'IDN',
    alpha2Code: 'ID',
    numericCode: 360,
    region: 'Asia',
    subregion: 'South-Eastern Asia',
  },
  {
    name: 'Iran',
    code: 'IRN',
    alpha2Code: 'IR',
    numericCode: 364,
    region: 'Asia',
    subregion: 'Southern Asia',
  },
  {
    name: 'Iraq',
    code: 'IRQ',
    alpha2Code: 'IQ',
    numericCode: 368,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Ireland',
    code: 'IRL',
    alpha2Code: 'IE',
    numericCode: 372,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Isle of Man',
    code: 'IMN',
    alpha2Code: 'IM',
    numericCode: 833,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Israel',
    code: 'ISR',
    alpha2Code: 'IL',
    numericCode: 376,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Italy',
    code: 'ITA',
    alpha2Code: 'IT',
    numericCode: 380,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Ivory Coast',
    code: 'CIV',
    alpha2Code: 'CI',
    numericCode: 384,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Jamaica',
    code: 'JAM',
    alpha2Code: 'JM',
    numericCode: 388,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Japan',
    code: 'JPN',
    alpha2Code: 'JP',
    numericCode: 392,
    region: 'Asia',
    subregion: 'Eastern Asia',
  },
  {
    name: 'Jersey',
    code: 'JEY',
    alpha2Code: 'JE',
    numericCode: 832,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Jordan',
    code: 'JOR',
    alpha2Code: 'JO',
    numericCode: 400,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Kazakhstan',
    code: 'KAZ',
    alpha2Code: 'KZ',
    numericCode: 398,
    region: 'Asia',
    subregion: 'Central Asia',
  },
  {
    name: 'Kenya',
    code: 'KEN',
    alpha2Code: 'KE',
    numericCode: 404,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Kiribati',
    code: 'KIR',
    alpha2Code: 'KI',
    numericCode: 296,
    region: 'Oceania',
    subregion: 'Micronesia',
  },
  {
    name: 'Kuwait',
    code: 'KWT',
    alpha2Code: 'KW',
    numericCode: 414,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Kyrgyzstan',
    code: 'KGZ',
    alpha2Code: 'KG',
    numericCode: 417,
    region: 'Asia',
    subregion: 'Central Asia',
  },
  {
    name: "Lao People's Democratic Republic",
    code: 'LAO',
    alpha2Code: 'LA',
    numericCode: 418,
    region: 'Asia',
    subregion: 'South-Eastern Asia',
  },
  {
    name: 'Latvia',
    code: 'LVA',
    alpha2Code: 'LV',
    numericCode: 428,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Lebanon',
    code: 'LBN',
    alpha2Code: 'LB',
    numericCode: 422,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Lesotho',
    code: 'LSO',
    alpha2Code: 'LS',
    numericCode: 426,
    region: 'Africa',
    subregion: 'Southern Africa',
  },
  {
    name: 'Liberia',
    code: 'LBR',
    alpha2Code: 'LR',
    numericCode: 430,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Libya',
    code: 'LBY',
    alpha2Code: 'LY',
    numericCode: 434,
    region: 'Africa',
    subregion: 'Northern Africa',
  },
  {
    name: 'Liechtenstein',
    code: 'LIE',
    alpha2Code: 'LI',
    numericCode: 438,
    region: 'Europe',
    subregion: 'Western Europe',
  },
  {
    name: 'Lithuania',
    code: 'LTU',
    alpha2Code: 'LT',
    numericCode: 440,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Luxembourg',
    code: 'LUX',
    alpha2Code: 'LU',
    numericCode: 442,
    region: 'Europe',
    subregion: 'Western Europe',
  },
  {
    name: 'Macao',
    code: 'MAC',
    alpha2Code: 'MO',
    numericCode: 446,
    region: 'Asia',
    subregion: 'Eastern Asia',
  },
  {
    name: 'Macedonia',
    code: 'MKD',
    alpha2Code: 'MK',
    numericCode: 807,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Madagascar',
    code: 'MDG',
    alpha2Code: 'MG',
    numericCode: 450,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Malawi',
    code: 'MWI',
    alpha2Code: 'MW',
    numericCode: 454,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Malaysia',
    code: 'MYS',
    alpha2Code: 'MY',
    numericCode: 458,
    region: 'Asia',
    subregion: 'South-Eastern Asia',
  },
  {
    name: 'Maldives',
    code: 'MDV',
    alpha2Code: 'MV',
    numericCode: 462,
    region: 'Asia',
    subregion: 'Southern Asia',
  },
  {
    name: 'Mali',
    code: 'MLI',
    alpha2Code: 'ML',
    numericCode: 466,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Malta',
    code: 'MLT',
    alpha2Code: 'MT',
    numericCode: 470,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Marshall Islands',
    code: 'MHL',
    alpha2Code: 'MH',
    numericCode: 584,
    region: 'Oceania',
    subregion: 'Micronesia',
  },
  {
    name: 'Martinique',
    code: 'MTQ',
    alpha2Code: 'MQ',
    numericCode: 474,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Mauritania',
    code: 'MRT',
    alpha2Code: 'MR',
    numericCode: 478,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Mauritius',
    code: 'MUS',
    alpha2Code: 'MU',
    numericCode: 480,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Mayotte',
    code: 'MYT',
    alpha2Code: 'YT',
    numericCode: 175,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Mexico',
    code: 'MEX',
    alpha2Code: 'MX',
    numericCode: 484,
    region: 'Americas',
    subregion: 'Northern America',
  },
  {
    name: 'Micronesia (Federated States of)',
    code: 'FSM',
    alpha2Code: 'FM',
    numericCode: 583,
    region: 'Oceania',
    subregion: 'Micronesia',
  },
  {
    name: 'Moldova',
    code: 'MDA',
    alpha2Code: 'MD',
    numericCode: 498,
    region: 'Europe',
    subregion: 'Eastern Europe',
  },
  {
    name: 'Monaco',
    code: 'MCO',
    alpha2Code: 'MC',
    numericCode: 492,
    region: 'Europe',
    subregion: 'Western Europe',
  },
  {
    name: 'Mongolia',
    code: 'MNG',
    alpha2Code: 'MN',
    numericCode: 496,
    region: 'Asia',
    subregion: 'Eastern Asia',
  },
  {
    name: 'Montenegro',
    code: 'MNE',
    alpha2Code: 'ME',
    numericCode: 499,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Montserrat',
    code: 'MSR',
    alpha2Code: 'MS',
    numericCode: 500,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Morocco',
    code: 'MAR',
    alpha2Code: 'MA',
    numericCode: 504,
    region: 'Africa',
    subregion: 'Northern Africa',
  },
  {
    name: 'Mozambique',
    code: 'MOZ',
    alpha2Code: 'MZ',
    numericCode: 508,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Myanmar',
    code: 'MMR',
    alpha2Code: 'MM',
    numericCode: 104,
    region: 'Asia',
    subregion: 'South-Eastern Asia',
  },
  {
    name: 'Namibia',
    code: 'NAM',
    alpha2Code: 'NA',
    numericCode: 516,
    region: 'Africa',
    subregion: 'Southern Africa',
  },
  {
    name: 'Nauru',
    code: 'NRU',
    alpha2Code: 'NR',
    numericCode: 520,
    region: 'Oceania',
    subregion: 'Micronesia',
  },
  {
    name: 'Nepal',
    code: 'NPL',
    alpha2Code: 'NP',
    numericCode: 524,
    region: 'Asia',
    subregion: 'Southern Asia',
  },
  {
    name: 'Netherlands',
    code: 'NLD',
    alpha2Code: 'NL',
    numericCode: 528,
    region: 'Europe',
    subregion: 'Western Europe',
  },
  {
    name: 'New Caledonia',
    code: 'NCL',
    alpha2Code: 'NC',
    numericCode: 540,
    region: 'Oceania',
    subregion: 'Melanesia',
  },
  {
    name: 'New Zealand',
    code: 'NZL',
    alpha2Code: 'NZ',
    numericCode: 554,
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
  },
  {
    name: 'Nicaragua',
    code: 'NIC',
    alpha2Code: 'NI',
    numericCode: 558,
    region: 'Americas',
    subregion: 'Central America',
  },
  {
    name: 'Niger',
    code: 'NER',
    alpha2Code: 'NE',
    numericCode: 562,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Nigeria',
    code: 'NGA',
    alpha2Code: 'NG',
    numericCode: 566,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Niue',
    code: 'NIU',
    alpha2Code: 'NU',
    numericCode: 570,
    region: 'Oceania',
    subregion: 'Polynesia',
  },
  {
    name: 'Norfolk Island',
    code: 'NFK',
    alpha2Code: 'NF',
    numericCode: 574,
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
  },
  {
    name: "Korea (Democratic People's Republic of)",
    code: 'PRK',
    alpha2Code: 'KP',
    numericCode: 408,
    region: 'Asia',
    subregion: 'Eastern Asia',
  },
  {
    name: 'Northern Mariana Islands',
    code: 'MNP',
    alpha2Code: 'MP',
    numericCode: 580,
    region: 'Oceania',
    subregion: 'Micronesia',
  },
  {
    name: 'Norway',
    code: 'NOR',
    alpha2Code: 'NO',
    numericCode: 578,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Oman',
    code: 'OMN',
    alpha2Code: 'OM',
    numericCode: 512,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Pakistan',
    code: 'PAK',
    alpha2Code: 'PK',
    numericCode: 586,
    region: 'Asia',
    subregion: 'Southern Asia',
  },
  {
    name: 'Palau',
    code: 'PLW',
    alpha2Code: 'PW',
    numericCode: 585,
    region: 'Oceania',
    subregion: 'Micronesia',
  },
  {
    name: 'Palestine, State of',
    code: 'PSE',
    alpha2Code: 'PS',
    numericCode: 275,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Panama',
    code: 'PAN',
    alpha2Code: 'PA',
    numericCode: 591,
    region: 'Americas',
    subregion: 'Central America',
  },
  {
    name: 'Papua New Guinea',
    code: 'PNG',
    alpha2Code: 'PG',
    numericCode: 598,
    region: 'Oceania',
    subregion: 'Melanesia',
  },
  {
    name: 'Paraguay',
    code: 'PRY',
    alpha2Code: 'PY',
    numericCode: 600,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'Peru',
    code: 'PER',
    alpha2Code: 'PE',
    numericCode: 604,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'Philippines',
    code: 'PHL',
    alpha2Code: 'PH',
    numericCode: 608,
    region: 'Asia',
    subregion: 'South-Eastern Asia',
  },
  {
    name: 'Pitcairn',
    code: 'PCN',
    alpha2Code: 'PN',
    numericCode: 612,
    region: 'Oceania',
    subregion: 'Polynesia',
  },
  {
    name: 'Poland',
    code: 'POL',
    alpha2Code: 'PL',
    numericCode: 616,
    region: 'Europe',
    subregion: 'Eastern Europe',
  },
  {
    name: 'Portugal',
    code: 'PRT',
    alpha2Code: 'PT',
    numericCode: 620,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Puerto Rico',
    code: 'PRI',
    alpha2Code: 'PR',
    numericCode: 630,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Qatar',
    code: 'QAT',
    alpha2Code: 'QA',
    numericCode: 634,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Republic of Kosovo',
    code: 'KOS',
    alpha2Code: 'XK',
    numericCode: 383,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Réunion',
    code: 'REU',
    alpha2Code: 'RE',
    numericCode: 638,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Romania',
    code: 'ROU',
    alpha2Code: 'RO',
    numericCode: 642,
    region: 'Europe',
    subregion: 'Eastern Europe',
  },
  {
    name: 'Russian Federation',
    code: 'RUS',
    alpha2Code: 'RU',
    numericCode: 643,
    region: 'Europe',
    subregion: 'Eastern Europe',
  },
  {
    name: 'Rwanda',
    code: 'RWA',
    alpha2Code: 'RW',
    numericCode: 646,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Saint Barthélemy',
    code: 'BLM',
    alpha2Code: 'BL',
    numericCode: 652,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    code: 'SHN',
    alpha2Code: 'SH',
    numericCode: 654,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Saint Kitts and Nevis',
    code: 'KNA',
    alpha2Code: 'KN',
    numericCode: 659,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Saint Lucia',
    code: 'LCA',
    alpha2Code: 'LC',
    numericCode: 662,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Saint Martin (French part)',
    code: 'MAF',
    alpha2Code: 'MF',
    numericCode: 663,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Saint Pierre and Miquelon',
    code: 'SPM',
    alpha2Code: 'PM',
    numericCode: 666,
    region: 'Americas',
    subregion: 'Northern America',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VCT',
    alpha2Code: 'VC',
    numericCode: 670,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Samoa',
    code: 'WSM',
    alpha2Code: 'WS',
    numericCode: 882,
    region: 'Oceania',
    subregion: 'Polynesia',
  },
  {
    name: 'San Marino',
    code: 'SMR',
    alpha2Code: 'SM',
    numericCode: 674,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Sao Tome and Principe',
    code: 'STP',
    alpha2Code: 'ST',
    numericCode: 678,
    region: 'Africa',
    subregion: 'Middle Africa',
  },
  {
    name: 'Saudi Arabia',
    code: 'SAU',
    alpha2Code: 'SA',
    numericCode: 682,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Senegal',
    code: 'SEN',
    alpha2Code: 'SN',
    numericCode: 686,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Serbia',
    code: 'SRB',
    alpha2Code: 'RS',
    numericCode: 688,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Seychelles',
    code: 'SYC',
    alpha2Code: 'SC',
    numericCode: 690,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Sierra Leone',
    code: 'SLE',
    alpha2Code: 'SL',
    numericCode: 694,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Singapore',
    code: 'SGP',
    alpha2Code: 'SG',
    numericCode: 702,
    region: 'Asia',
    subregion: 'South-Eastern Asia',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    code: 'SXM',
    alpha2Code: 'SX',
    numericCode: 534,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Slovakia',
    code: 'SVK',
    alpha2Code: 'SK',
    numericCode: 703,
    region: 'Europe',
    subregion: 'Eastern Europe',
  },
  {
    name: 'Slovenia',
    code: 'SVN',
    alpha2Code: 'SI',
    numericCode: 705,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Solomon Islands',
    code: 'SLB',
    alpha2Code: 'SB',
    numericCode: 90,
    region: 'Oceania',
    subregion: 'Melanesia',
  },
  {
    name: 'Somalia',
    code: 'SOM',
    alpha2Code: 'SO',
    numericCode: 706,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'South Africa',
    code: 'ZAF',
    alpha2Code: 'ZA',
    numericCode: 710,
    region: 'Africa',
    subregion: 'Southern Africa',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    code: 'SGS',
    alpha2Code: 'GS',
    numericCode: 239,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'Korea (Republic of)',
    code: 'KOR',
    alpha2Code: 'KR',
    numericCode: 410,
    region: 'Asia',
    subregion: 'Eastern Asia',
  },
  {
    name: 'South Sudan',
    code: 'SSD',
    alpha2Code: 'SS',
    numericCode: 728,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Spain',
    code: 'ESP',
    alpha2Code: 'ES',
    numericCode: 724,
    region: 'Europe',
    subregion: 'Southern Europe',
  },
  {
    name: 'Sri Lanka',
    code: 'LKA',
    alpha2Code: 'LK',
    numericCode: 144,
    region: 'Asia',
    subregion: 'Southern Asia',
  },
  {
    name: 'Sudan',
    code: 'SDN',
    alpha2Code: 'SD',
    numericCode: 729,
    region: 'Africa',
    subregion: 'Northern Africa',
  },
  {
    name: 'Suriname',
    code: 'SUR',
    alpha2Code: 'SR',
    numericCode: 740,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'Svalbard and Jan Mayen',
    code: 'SJM',
    alpha2Code: 'SJ',
    numericCode: 744,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Swaziland',
    code: 'SWZ',
    alpha2Code: 'SZ',
    numericCode: 748,
    region: 'Africa',
    subregion: 'Southern Africa',
  },
  {
    name: 'Sweden',
    code: 'SWE',
    alpha2Code: 'SE',
    numericCode: 752,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'Switzerland',
    code: 'CHE',
    alpha2Code: 'CH',
    numericCode: 756,
    region: 'Europe',
    subregion: 'Western Europe',
  },
  {
    name: 'Syrian Arab Republic',
    code: 'SYR',
    alpha2Code: 'SY',
    numericCode: 760,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Taiwan',
    code: 'TWN',
    alpha2Code: 'TW',
    numericCode: 158,
    region: 'Asia',
    subregion: 'Eastern Asia',
  },
  {
    name: 'Tajikistan',
    code: 'TJK',
    alpha2Code: 'TJ',
    numericCode: 762,
    region: 'Asia',
    subregion: 'Central Asia',
  },
  {
    name: 'Tanzania, United Republic of',
    code: 'TZA',
    alpha2Code: 'TZ',
    numericCode: 834,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Thailand',
    code: 'THA',
    alpha2Code: 'TH',
    numericCode: 764,
    region: 'Asia',
    subregion: 'South-Eastern Asia',
  },
  {
    name: 'Timor-Leste',
    code: 'TLS',
    alpha2Code: 'TL',
    numericCode: 626,
    region: 'Asia',
    subregion: 'South-Eastern Asia',
  },
  {
    name: 'Togo',
    code: 'TGO',
    alpha2Code: 'TG',
    numericCode: 768,
    region: 'Africa',
    subregion: 'Western Africa',
  },
  {
    name: 'Tokelau',
    code: 'TKL',
    alpha2Code: 'TK',
    numericCode: 772,
    region: 'Oceania',
    subregion: 'Polynesia',
  },
  {
    name: 'Tonga',
    code: 'TON',
    alpha2Code: 'TO',
    numericCode: 776,
    region: 'Oceania',
    subregion: 'Polynesia',
  },
  {
    name: 'Trinidad and Tobago',
    code: 'TTO',
    alpha2Code: 'TT',
    numericCode: 780,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Tunisia',
    code: 'TUN',
    alpha2Code: 'TN',
    numericCode: 788,
    region: 'Africa',
    subregion: 'Northern Africa',
  },
  {
    name: 'Turkey',
    code: 'TUR',
    alpha2Code: 'TR',
    numericCode: 792,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Turkmenistan',
    code: 'TKM',
    alpha2Code: 'TM',
    numericCode: 795,
    region: 'Asia',
    subregion: 'Central Asia',
  },
  {
    name: 'Turks and Caicos Islands',
    code: 'TCA',
    alpha2Code: 'TC',
    numericCode: 796,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Tuvalu',
    code: 'TUV',
    alpha2Code: 'TV',
    numericCode: 798,
    region: 'Oceania',
    subregion: 'Polynesia',
  },
  {
    name: 'Uganda',
    code: 'UGA',
    alpha2Code: 'UG',
    numericCode: 800,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Ukraine',
    code: 'UKR',
    alpha2Code: 'UA',
    numericCode: 804,
    region: 'Europe',
    subregion: 'Eastern Europe',
  },
  {
    name: 'United Arab Emirates',
    code: 'ARE',
    alpha2Code: 'AE',
    numericCode: 784,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'United Kingdom',
    code: 'GBR',
    alpha2Code: 'GB',
    numericCode: 826,
    region: 'Europe',
    subregion: 'Northern Europe',
  },
  {
    name: 'United States',
    code: 'USA',
    alpha2Code: 'US',
    numericCode: 840,
    region: 'Americas',
    subregion: 'Northern America',
  },
  {
    name: 'United States Minor Outlying Islands',
    code: 'UMI',
    alpha2Code: 'UM',
    numericCode: 581,
    region: 'Americas',
    subregion: 'Northern America',
  },
  {
    name: 'Uruguay',
    code: 'URY',
    alpha2Code: 'UY',
    numericCode: 858,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'Uzbekistan',
    code: 'UZB',
    alpha2Code: 'UZ',
    numericCode: 860,
    region: 'Asia',
    subregion: 'Central Asia',
  },
  {
    name: 'Vanuatu',
    code: 'VUT',
    alpha2Code: 'VU',
    numericCode: 548,
    region: 'Oceania',
    subregion: 'Melanesia',
  },
  {
    name: 'Venezuela',
    code: 'VEN',
    alpha2Code: 'VE',
    numericCode: 862,
    region: 'Americas',
    subregion: 'South America',
  },
  {
    name: 'Viet Nam',
    code: 'VNM',
    alpha2Code: 'VN',
    numericCode: 704,
    region: 'Asia',
    subregion: 'South-Eastern Asia',
  },
  {
    name: 'Virgin Islands (British)',
    code: 'VGB',
    alpha2Code: 'VG',
    numericCode: 92,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Virgin Islands (U.S.)',
    code: 'VIR',
    alpha2Code: 'VI',
    numericCode: 850,
    region: 'Americas',
    subregion: 'Caribbean',
  },
  {
    name: 'Wallis and Futuna',
    code: 'WLF',
    alpha2Code: 'WF',
    numericCode: 876,
    region: 'Oceania',
    subregion: 'Polynesia',
  },
  {
    name: 'Western Sahara',
    code: 'ESH',
    alpha2Code: 'EH',
    numericCode: 732,
    region: 'Africa',
    subregion: 'Northern Africa',
  },
  {
    name: 'Yemen',
    code: 'YEM',
    alpha2Code: 'YE',
    numericCode: 887,
    region: 'Asia',
    subregion: 'Western Asia',
  },
  {
    name: 'Zambia',
    code: 'ZMB',
    alpha2Code: 'ZM',
    numericCode: 894,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
  {
    name: 'Zimbabwe',
    code: 'ZWE',
    alpha2Code: 'ZW',
    numericCode: 716,
    region: 'Africa',
    subregion: 'Eastern Africa',
  },
];
